### ISSUE TITLE
опечатки

### ISSUE THREAD

**Issue by yogggoy** [vectozavr/learn_3dzavr#2]
1.  README.md
https://github.com/vectozavr/learn_3dzavr/blob/0e215f3762ea3836464aa326d5c1b0f72c6c572a/README.md?plain=1#LL22C4-L22C4
кл**И**нируйте

2.  README.md
Ошибка в нумерации пунктов 1-2-**2**-3-4. Хотя Markdown автоматически исправил это в режиме форматирования. Забавно.

4. lesson8.cpp
в комментах ссылка на файлы .срр, а должна быть ссылка на .h хэдэры
     * engine/animation/ATranslate.cpp
     * engine/animation/ARotate.cpp
     * engine/animation/AScale.cpp

**Comment by vectozavr** [comment]
Fixed, thank you!
